# Coins needed for each tier upgrade (Tier 1 is not included as it is default)
tier-2-upgrade-cost: 50
tier-3-upgrade-cost: 125
tier-4-upgrade-cost: 300
tier-5-upgrade-cost: 600
tier-6-upgrade-cost: 3500
tier-7-upgrade-cost: 6500
tier-8-upgrade-cost: 8500
tier-9-upgrade-cost: 14000

# Descriptions for each tier upgrade seperated by \n
zombie-tier-1-upgrade-description: ""
zombie-tier-2-upgrade-description: ""
zombie-tier-3-upgrade-description: ""
zombie-tier-4-upgrade-description: ""
zombie-tier-5-upgrade-description: ""
zombie-tier-6-upgrade-description: ""
zombie-tier-7-upgrade-description: ""
zombie-tier-8-upgrade-description: ""
zombie-tier-9-upgrade-description: ""

skeleton-tier-1-upgrade-description: ""
skeleton-tier-2-upgrade-description: ""
skeleton-tier-3-upgrade-description: ""
skeleton-tier-4-upgrade-description: ""
skeleton-tier-5-upgrade-description: ""
skeleton-tier-6-upgrade-description: ""
skeleton-tier-7-upgrade-description: ""
skeleton-tier-8-upgrade-description: ""
skeleton-tier-9-upgrade-description: ""

herobrine-tier-1-upgrade-description: ""
herobrine-tier-2-upgrade-description: ""
herobrine-tier-3-upgrade-description: ""
herobrine-tier-4-upgrade-description: ""
herobrine-tier-5-upgrade-description: ""
herobrine-tier-6-upgrade-description: ""
herobrine-tier-7-upgrade-description: ""
herobrine-tier-8-upgrade-description: ""
herobrine-tier-9-upgrade-description: ""

creeper-tier-1-upgrade-description: ""
creeper-tier-2-upgrade-description: ""
creeper-tier-3-upgrade-description: ""
creeper-tier-4-upgrade-description: ""
creeper-tier-5-upgrade-description: ""
creeper-tier-6-upgrade-description: ""
creeper-tier-7-upgrade-description: ""
creeper-tier-8-upgrade-description: ""
creeper-tier-9-upgrade-description: ""

spirit_warrior-tier-1-upgrade-description: ""
spirit_warrior-tier-2-upgrade-description: ""
spirit_warrior-tier-3-upgrade-description: ""
spirit_warrior-tier-4-upgrade-description: ""
spirit_warrior-tier-5-upgrade-description: ""
spirit_warrior-tier-6-upgrade-description: ""
spirit_warrior-tier-7-upgrade-description: ""
spirit_warrior-tier-8-upgrade-description: ""
spirit_warrior-tier-9-upgrade-description: ""

wither_minion-tier-1-upgrade-description: ""
wither_minion-tier-2-upgrade-description: ""
wither_minion-tier-3-upgrade-description: ""
wither_minion-tier-4-upgrade-description: ""
wither_minion-tier-5-upgrade-description: ""
wither_minion-tier-6-upgrade-description: ""
wither_minion-tier-7-upgrade-description: ""
wither_minion-tier-8-upgrade-description: ""
wither_minion-tier-9-upgrade-description: ""