name: MegaArena
main: com.andrewyunt.megaarena.MegaArena
version: 1.0
softdepend: [Vault,StaffPlus,EffectLib]

############################################################
# +------------------------------------------------------+ #
# |                       Commands                       | #
# +------------------------------------------------------+ #
############################################################
commands:
  arena:
    description: Base command for managing arenas.
    permission: megaarena.arena
  duel:
    description: Request to duel a player.
    permission: megaarena.duel
  duelaccept:
    description: Accept a request to duel a player.
    permission: megaarena.duelaccept
  dueldeny:
    description: Deny a request to duel a player.
    permission: megaarena.dueldeny

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################
permissions:
   megaarena.*:
     description: Gives access to all MegaArena commands.
     children:
       megaarena.arena: true
       megaarena.createarena: true
       megaarena.deletearena: true
       megaarena.addspawn: true
       megaarena.removespawn: true
       megaarena.duel: true
       megaarena.duelaccept: true
   megaarena.arena.*:
     description: Gives access to all MegaArena arena management commands.
     children:
       megaarena.arena: true
       megaarena.arena.create: true
       megaarena.arena.delete: true
       megaarena.arena.addspawn: true
       megaarena.arena.removespawn: true
   megaarena.arena.help:
     description: Gives you access to the arena help menu.
     default: op
   megaarena.arena.create:
     description: Allows you to create an arena.
     default: op
   megaarena.arena.delete:
     description: Allows you to delete an existing arena.
     default: op
   megaarena.arena.select:
     description: Allows you to select an existing arena.
     default: op
   megaarena.arena.edit:
     description: Allows you to edit an existing arena.
     default: op
   megaarena.arena.addspawn:
     description: Allows you to add a spawn to an existing arena.
     default: op
   megaarena.arena.removespawn:
     description: Allows you to remove a spawn from an existing arena.
     default: op
   megaarena.arena.list:
     description: Allows you to list all arenas.
     default: op
   megaarena.duel:
     description: Allows you to request to duel a player.
     default: true
   megaarena.duelaccept:
     description: Allows you to accept a duel from another player.
     default: true
   megaarena.dueldeny:
     description: Allows you to deny a duel from another player.
     default: true