name: ArenaPlugin
main: com.andrewyunt.arenaplugin.ArenaPlugin
version: 1.0
softdepend: [Vault,StaffPlus,TagAPI]

############################################################
# +------------------------------------------------------+ #
# |                       Commands                       | #
# +------------------------------------------------------+ #
############################################################
commands:
  arena:
    description: Base command for managing arenas.
    permission: arenaplugin.arena
  duel:
    description: Request to duel a player.
    permission: arenaplugin.duel
  duelaccept:
    description: Accept a request to duel a player.
    permission: arenaplugin.duelaccept
  dueldeny:
    description: Deny a request to duel a player.
    permission: arenaplugin.dueldeny

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################
permissions:
   arenaplugin.*:
     description: Gives access to all ArenaPlugin commands.
     children:
       arenaplugin.arena: true
       arenaplugin.createarena: true
       arenaplugin.deletearena: true
       arenaplugin.addspawn: true
       arenaplugin.removespawn: true
       arenaplugin.duel: true
       arenaplugin.duelaccept: true
   arenaplugin.arena.*:
     description: Gives access to all ArenaPlugin arena management commands.
     children:
       arenaplugin.arena: true
       arenaplugin.arena.create: true
       arenaplugin.arena.delete: true
       arenaplugin.arena.addspawn: true
       arenaplugin.arena.removespawn: true
   arenaplugin.arena.help:
     description: Gives you access to the arena help menu.
     default: op
   arenaplugin.arena.create:
     description: Allows you to create an arena.
     default: op
   arenaplugin.arena.delete:
     description: Allows you to delete an existing arena.
     default: op
   arenaplugin.arena.select:
     description: Allows you to select an existing arena.
     default: op
   arenaplugin.arena.edit:
     description: Allows you to edit an existing arena.
     default: op
   arenaplugin.arena.addspawn:
     description: Allows you to add a spawn to an existing arena.
     default: op
   arenaplugin.arena.removespawn:
     description: Allows you to remove a spawn from an existing arena.
     default: op
   arenaplugin.arena.list:
     description: Allows you to list all arenas.
     default: op
   arenaplugin.duel:
     description: Allows you to request to duel a player.
     default: true
   arenaplugin.duelaccept:
     description: Allows you to accept a duel from another player.
     default: true
   arenaplugin.dueldeny:
     description: Allows you to deny a duel from another player.
     default: true