name: MegaArena
main: com.andrewyunt.megaarena.MegaArena
version: 1.2

############################################################
# +------------------------------------------------------+ #
# |                       Commands                       | #
# +------------------------------------------------------+ #
############################################################
commands:
  arena:
    description: Base command for managing arenas.
  duel:
    description: Request to duel a player.
    permission: megaarena.duel
  duelaccept:
    description: Accept a request to duel a player.
    permission: megaarena.duelaccept
  dueldeny:
    description: Deny a request to duel a player.
    permission: megaarena.dueldeny
  duelstoggle:
    description: Toggle receiving duel requests from players on or off.
    permission: megaarena.duelstoggle
  bloodtoggle:
    description: Toggle blood particles on or off..
    permission: megaarena.bloodtoggle
  spawn:
    description: Kills the player if they are in a normal FFA or TDM arena.
    permission: megaarena.spawn

############################################################
# +------------------------------------------------------+ #
# |                      Permissions                     | #
# +------------------------------------------------------+ #
############################################################
permissions:
   megaarena.*:
     description: Gives access to all MegaArena commands.
     children:
       megaarena.arena.*: true
       megaarena.spawn: true
       megaarena.bloodtoggle: true
       megaarena.duelstoggle: true
       megaarena.duel: true
       megaarena.duelaccept: true
       megaarena.dueldeny: true
       megaarena.coins.double: true
       megaarena.coins.triple: true
   megaarena.arena.*:
     description: Gives access to all MegaArena arena management commands.
     children:
       megaarena.arena.create: true
       megaarena.arena.delete: true
       megaarena.arena.select: true
       megaarena.arena.edit: true
       megaarena.arena.addspawn: true
       megaarena.arena.removespawn: true
       megaarena.arena.setqueuelocation: true
       megaarena.arena.list: true
       megaarena.arena.help: true
   megaarena.arena.help:
     description: Gives you access to the arena help menu.
     default: op
   megaarena.arena.create:
     description: Allows you to create an arena.
     default: op
   megaarena.arena.delete:
     description: Allows you to delete an existing arena.
     default: op
   megaarena.arena.select:
     description: Allows you to select an existing arena.
     default: op
   megaarena.arena.edit:
     description: Allows you to edit an existing arena.
     default: op
   megaarena.arena.addspawn:
     description: Allows you to add a spawn to an existing arena.
     default: op
   megaarena.arena.removespawn:
     description: Allows you to remove a spawn from an existing arena.
     default: op
   megaarena.arena.list:
     description: Allows you to list all arenas.
     default: op
   megaarena.duel:
     description: Allows you to request to duel a player.
     default: true
   megaarena.duelaccept:
     description: Allows you to accept a duel from another player.
     default: true
   megaarena.dueldeny:
     description: Allows you to deny a duel from another player.
     default: true
   megaarena.duelstoggle:
     description: Allows you to toggle receiving duel requests on or off.
     default: true
   megaarena.bloodtoggle:
     description: Allows you to toggle blood particles on or off.
     default: true
   megaarena.spawn:
     description: Allows you to quit games.
     default: op
   megaarena.coins.double:
     description: Gives you 2x coins.
     default: op
   megaarena.coins.triple:
     description: Gives you 3x coins.
     default: op